

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'
  server:
    port: 8081

server:
  port: 8080

spring:
  application:
    name: uaa

  messages:
    encoding: UTF-8
    always-use-message-format: false
    basename: message
    fallback-to-system-locale: true
    use-code-as-default-message: false

  datasource:
    # 数据库驱动
    driver-class-name: org.h2.Driver
    # 数据库密码
    password: ""
    # 数据库连接ur，为了兼容mysql,添加 ,MODE=MySQL
    # ;DATABASE_TO_LOWER=TRUE 是让表名转为小写
    # ;CASE_INSENSITIVE_IDENTIFIERS=TRUE 不区分大小写
    # ; DB_CLOSE_DELAY = -1 不自动关闭数据库连接
    url: jdbc:h2:mem:test;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;DB_CLOSE_DELAY=-1
    # 数据库用户名
    username: sa

  redis:
    host: localhost
    port: 6379
    database: 15

  sql:
    init:
      mode: embedded

  jpa:
    hibernate:
      ddl-auto: create-drop

    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        # 禁止输出 Trace信息
        trace: false
        # 禁止远程访问h2管理界面
        web-allow-others: false

  thymeleaf:
    cache: false

  ldap:
    base: dc=imooc,dc=com
    embedded:
      base-dn: dc=imooc,dc=com
      ldif: classpath:test-ldap-server.ldif
      port: 8389
    urls: ldap://localhost:8389/
  mail:
    default-encoding: UTF-8
    host: ${SMTP_HOST}
    password: ${SMTP_PASSWORD}
    port: ${SMTP_PORT}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: ${SMTP_USERNAME}



