logging:
  pattern:
    console: '%clr(%d{E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n'
  level:
    org.springframework.security: DEBUG
    com.guludoc.learning.u3app.uaa: DEBUG

spring:
  messages:
    basename: message
    encoding: UTF-8
server:
  port: ${SERVER_PORT:8080}

imooc:
  jwt:
    access-token-expire-time: 300000
    refresh-token-expire-time: 2592000000

  ali:
    api-key: ${ALI_API_KEY | ""}
    api-secret: ${ALI_API_SECRET | ""}

  message-provider:
    name: console
    api-url: ""

  email-provider:
    name: console
    api-key: ${EMAIL_API_KEY}