logging:
  pattern:
    console: '%clr(%d{E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n'
  level:
    org.springframework.security: DEBUG
    com.guludoc.learning.u3app.uaa: DEBUG

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'
  server:
    port: 8081

server:
  port: 8080

spring:
  application:
    name: uaa

  datasource:
    # 数据库驱动
    driver-class-name: org.h2.Driver
    # 数据库密码
    password: ""
    # 数据库连接ur，为了兼容mysql,添加 ,MODE=MySQL
    # ;DATABASE_TO_LOWER=TRUE 是让表名转为小写
    # ;CASE_INSENSITIVE_IDENTIFIERS=TRUE 不区分大小写
    # ; DB_CLOSE_DELAY = -1 不自动关闭数据库连接
    url: jdbc:h2:mem:test;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;DB_CLOSE_DELAY=-1
    # 数据库用户名
    username: sa

  sql:
    init:
      mode: embedded
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        # 禁止输出 Trace信息
        trace: false
        # 禁止远程访问h2管理界面
        web-allow-others: false

  thymeleaf:
    cache: false

