version: "3.3"
services:
  mysql:
    image: library/mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=security
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    command: mysqld --default-authentication-plugin=mysql_native_password --lower_case_table_name=true

  redis:
    image: library/redis:6-alpine
    environment:
      TZ: Asia/Shanghai
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    command: ["redis-server", "--production-mode", "no"]


volumes:
  mysql-data: {}
  redis-data: {}
