

###
# @name wrong crediential
POST {{host}}/authorize/token
Content-Type: application/json

{
  "username": "user",
  "password": "13444"
}

###
# @name getToken
POST {{host}}/authorize/token
Content-Type: application/json

{
  "username": "user",
  "password": "123"
}

> {%
client.global.set("accessToken", response.body.accessToken)
client.global.set("refreshToken", response.body.refreshToken)
%}

###
# @name refreshToken
POST {{host}}/authorize/refresh?refreshToken={{refreshToken}}
Authorization: Bearer {{accessToken}}

###
# @name register invalid
POST {{host}}/authorize/register
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "username": "billwen",
  "password": "Super@128.1",
  "matchPassword": "Super@128.1",
  "name": "张三",
  "email": "gang.wen@gmail.com",
  "mobile": "18651580683"
}