###
# @name PrincipalUser
GET {{host}}/api/principal
Authorization: Basic user 123

###
# @name PrincipalUser
GET {{host}}/api/principal
Authorization: Basic zhaoliu 12345

###
# @name PrincipalUser
GET {{host}}/api/principal
Authorization: Basic zhaoliu 123

###
# @name Use token - correct
GET {{host}}/api/principal
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJtb29jIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJzdWIiOiJ1c2VyIiwiaWF0IjoxNjczNTE3MDIwLCJleHAiOjE2NzM1MTczMjB9.FMWBIOieVxVoduya0Mi6T7xapDqywxTLKSUNGQw4JpZeQyzkhVRadHQhW7WKZUmKhFgOhJxz05_xw0F8sFShlQ

###
# @name Use token - failed
GET {{host}}/api/principal
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJtb29jIiwiYXV0aG9OlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJzdWIiOiJ1c2VyIiwiaWF0IjoxNjczNTE3MDIwLCJleHAiOjE2NzM1MTczMjB9.FMWBIOieVxVoduya0Mi6T7xapDqywxTLKSUNGQw4JpZeQyzkhVRadHQhW7WKZUmKhFgOhJxz05_xw0F8sFShlQ
